### PR TITLE
Allow a vendor id prefix in the board core value, as described in issue #49

### PR DESCRIPTION
**Pull request by aog2000a**
This very minimal commit allows to "workaround" the problem: you can get arduino-cmake to run successfully with a
`<BOARD>.build.core=arduino:arduino`
value, if the `<BOARD>_CORES_PATH` variable is correctly set. That is not possible without this commit.

### CODE REVIEW

**Comment by aog2000a** [comment]
It seems the Travis build on Mac for Arduino 1.6 failed due to a timeout downloading the Arduino package... i don't know how to retrigger it.

**Comment by aog2000a** [comment]
Uhm... it seems that all my commits in the same branch of my repo get automatically added to the pull request? I was expecting the pull request is for a single specific commit. Anyways the new commit adding a "ARDUINO_DEFAULT_BOARD_CPU" variable could also be pulled if you are interested.

**Comment by MrPointer** [comment]
@aog2000a Thanks for the additional change - It is valuable IMO and could be added.
However, it truly doesn't belong to this PR. Could you please revert the commit and open a new PR instead?

Regarding the original PR intent - We're currently discussing it as part of the #49 issue, so I'm closing this one until we'll decide how to 'attack' it properly.

**Comment by aog2000a** [comment]
Yes sorry, i now realize it should have been a different feature branch. Will do it, txs

**Pull request closed without merging**
