### PR TITLE
Enable build of shared libraries for x86 firmware simulations (III)

### PR DESCRIPTION
**Pull request by noseglasses**
This is #42 rebased on develop - second try.

### CODE REVIEW

**Comment by noseglasses** [comment]
I just checked the travis testing output. The build fails but it seems unrelated to this PR as there are problems with examples reported.

**Comment by noseglasses** [comment]
I just checked the travis testing output. The build fails but it seems unrelated to this PR as there are problems with examples reported.

**Comment by MrPointer** [comment]
It's not possible, this is the reason CI exists in this project - To avoid such questions.
The `develop` branch is perfectly valid right now, which means that there **is** an issue with your PR specifically, I'm sorry.

**Comment by noseglasses** [comment]
Fixed. Now travis tests mass successfully.

**Review by MrPointer — APPROVED** [review]
LGTM, thank you for contributing, yet again!

**Pull request merged**
