### PR TITLE
Version 2.0.0 Release

### PR DESCRIPTION
**Pull request by MrPointer**
Ah, such a great moment for this project!
It is finally time to integrate all our work into `master`, after finishing the release :)

@JonasProgrammer @fraillt I've added a Change-Log file, would like you to review it and suggest anything else to write there before completing the PR.

Thank you all for participating in our great adventure!

### CODE REVIEW

**Review by fraillt — DISMISSED** [review]

**Comment by fraillt** [comment]
What a great news!
I'm glad that I could participate in this adventure :)

Regarding `CHANGELOG` I think it's ok for this release, it was too many changes and too long time passed to recall all the bits that has been changed :)

**Review by JonasProgrammer — DISMISSED** [review]
LGTM

Can't say anything other than a huge 'thank you' for this incredible large revamp again.

I won't merge it, the honour of clicking this button shall be thine @MrPointer.

**Comment by MrPointer** [comment]
Fuck. I just wanted to update the release date to match the actual date (Has been Dec 11th, today is Dec 13th) so I changed the `CHANGELOG` file and force-pushed. If anyone had told me earlier that it will dismiss the reviews... 
@fraillt @JonasProgrammer Please approve the PR again so I could merge it, sorry :(

**Review by JonasProgrammer — APPROVED** [review]
+50 date correctness

LEBTM ;)

**Pull request merged**
