### PR TITLE
Extracted core functions

### PR DESCRIPTION
**Pull request by MrPointer**
### Refactoring by extraction
Extracted many core functions from the main `Arduino.cmake` script to separate, matching script files located under the **Core** directory.
Renamed few of the functions to better suited names.

As for the *Script-driven approach* discussed in #12 , the entire code is divided into scripts yet most of the scripts contain functions, which doesn't affect the approach since a new implementation of a function can be used by simply including a different script file.

### CODE REVIEW

**Review by JonasProgrammer — COMMENTED** [review]
LGTM refractoring-wise

Just a purely cosmetic request, could you add newlines to the end of the files ending in text? It's nothing functional, but common practice on unixoid systems and git is always chatty about it when diffing.

EDIT: Also before I forget, what do you think of having codestylesettings.xml in the repo? I'm usually against having IDE-related stuff there but it'd make collaborating easier as Alt+L won't reformat each others code on every occasion

**Comment by MrPointer** [comment]
@JonasProgrammer Sure, I thought I already added those, seems not 😆 
About the `codestylesettings.xml` - I'm also against having IDE-related stuff, but I think that a single config file such as this one wouldn't do any harm, **unless** people are going to mess with it on every single commit they make... After all, that's the purpose of not having them part of the repo.

**Review by JonasProgrammer — APPROVED** [review]
LGTM

Regarding codestyle stuff would you mind commiting yours then to some other branch? I don't think anyone would touch them unless really needed, the point is it simply makes it easier for either side to have a common base rather than checking what causes formatting hickups by hand.

**Comment by Souler** [comment]
Just commenting on the codestyle stuff, I really like [editorconfig](http://editorconfig.org/). It's tiny, non intrusive, easy to read and mantain, and most text editors [support it](http://editorconfig.org/#download) either by default or via plugin

**Comment by MrPointer** [comment]
@Souler LGTM.
But we should discuss it in a separate issue, as this is not exactly the right place to do so.

**Pull request merged**
