### PR TITLE
Turn all CMake functions and their use lowercase

### PR DESCRIPTION
**Pull request by noseglasses**
This PR turns all CMake and custom function definitions and their use lowercase.

# CMake stock functions
I did as follows
```bash
cmake --help-command-list \
    | while read c; do
        echo 's/\([^a-zA-Z_]\|^\)'"$c"'\(\s*\)(/\1'"$c"'\2(/gI'
    done > convert.sed
git ls-files -z -- '*CMakeLists.txt' | xargs -0 sed -i -f convert.sed
git ls-files -z -- '*.cmake' | xargs -0 sed -i -f convert.sed
```

# Custom functions

I generated the following sed file: https://gist.github.com/noseglasses/169e07a843b6efe3ea2a1f458139845a and used it as follows.
```bash
git ls-files -z -- '*CMakeLists.txt' | xargs -0 sed -i -f all_functions.sed
git ls-files -z -- '*.cmake' | xargs -0 sed -i -f all_functions.sed
```

Generating `all_functions.sed` works as follows:
1) Search for function definitions in cmake files.
```bash
find -name '*.cmake' | xargs sed -n '/\bfunction\s*(/{:start /)/!{N;b start};/[a-zA-Z0-9_]*/p}' > functions.txt
find -name '*CMakeLists.txt' | xargs sed -n '/\bfunction\s*(/{:start /)/!{N;b start};/[a-zA-Z0-9_]*/p}' >> functions.txt
```

2) Open `functions.txt` in a text editor, e.g. vi and remove everything apart from the function names, one per file.

3) Turn all function names upper case (vi: select all text and press U) and store the result as `functions_upper.txt`.

4) Copy  `functions_upper.txt` to `functions_lower.txt` and replace all upper case by lower case (e.g. using vi by marking all text and pressing u).

5) Paste both files 
```bash
paste -d '/' functions_upper.txt functions_lower.txt > all_functions.sed
```
6) Open `all_functions.sed` and replace all `/` with '\b/', all line starts with `s/\b` and all line ends with `/gI`.

### CODE REVIEW

**Comment by noseglasses** [comment]
The process described above could be repeated once in a while while Arduino-CMake evolves, to keep the project tidy with respect to case.

**Review by MrPointer — CHANGES_REQUESTED** [review]
Lol it seems like something got wrong and all functions have turned **uppercase** instead. Or maybe GitHub has gone crazy?

**Comment by noseglasses** [comment]
I could send you a picture of me blushing, but I won't :smile: 
Apparently I successfully changed case of all functions. That's good. What's not so good is that my final inspection passed because case changed. I should have my eyes checked. It seems I turned color blind and I developed difficulties telling left from right on top of it. 
Or maybe I just work too much.
Will submit a corrected PR ASAP.

**Comment by noseglasses** [comment]
Submitted PR #71 that fixes the case problem. Closing #70.

**Pull request closed without merging**
