### PR TITLE
support for usb boards and cleaner builds

### PR DESCRIPTION
**Pull request by fraillt**
- Added *CMAKE_CXX_STANDARD 11* required for USB support. Also added *-fno-threadsafe-statics* for CXX targets, because in C++11 static initialization is thread-safe, and compiler generates lock guards, which are not supported. This flag disables lock guards. We're in single thread anyway:)
- Added ASM language *project(ArduinoExample C CXX ASM)* and *setup_asm_flags* function. This is required for pulseIn function, e.g. Robot_Control library.
- BoardFlags reworked. Created separate functions to use with recommended CMake functions, e.g. target_compile_options:
  -	_get_arduino_version_define
  -	_get_board_compile_defines - list of defines, additionally added ARDUINO_<board_name> ARDUINO_ARCH_AVR USB_PRODUCT and USB_MANUFACTURER flags, they are used by some arduino libraries.
  -	_get_board_compile_options - list of options
  -	_get_board_compile_includes - list of includes
  -	_set_board_compile_flags, _set_board_link_flags - instead of returning compile options and later using depreceted CMAKE function *set_target_properties*, directly sets flags to target using non depreceted functions.
- Removed ARDUINO_LIBRARIES_PATH and ARDUINO_PLATFORM_LIBRARIES_PATH includes, they are totally unnecessary, because we need explicit path for each library that we get from *find_arduino_library* function.
- Some internal function signature has changed during refactoring.
  -	make_arduino_library - removed COMPILE_FLAGS and LINK_FLAGS parameters, and instead of returing one parameter now returns two parameters explicitly (LIB_TARGETS, LIB_INCLUDES)
  -	make_arduino_libraries - removed not used SRCS, COMPILE_FLAGS, LINK_FLAGS and instead added ARD_LIBS_PATH, and also returns two parameters explicitly (LIB_TARGETS, LIB_INCLUDES)
  -	create_arduino_target - removed unused LINK_FLAGS
	
- *find_arduino_library* was fixed, it falsly included local directory as library, even though it was not in compatible with arduino library structure. Now it works as is written in the comment.
> A Arduino library is a folder that has the same name as the include header.
> For example, if we have a include "#include <LibraryName.h>" then the following
> directory structure is considered a Arduino library:
> 
>    LibraryName/
>         |- LibraryName.h
>         `- LibraryName.c	
- *make_arduino_library* was fixed, it didn't returned include path for libraries that had a cmake target already created.
- updated compiler flags for C, CXX and ASM (new)
- new public function *override_usb_properties* to be able to customise USB defines for the board.
- new internal function *_override_board_property*, used to override values loaded from boards.txt.

These changes now enables to use boards with USB (leonardo, micro, one ... ) and additional *override_usb_properties* function should solve the problems in [#4](https://github.com/arduino-cmake/arduino-cmake/issues/4)

A lot has been changed, to make code more cleaner and readable, in the process some bugs was fixed. Also now builds are much cleaner, without any unnecessary includes or flags.

@MrPointer and @JonasProgrammer could you please help me to find better place for *override_usb_properties* function?
Currently I added it in Platform\Core\BoardPropertiesReader.cmake. 
I was thinking maybe it would make sense to create separate folder to store all public/user functions, it would be easier to find out if a function can change its signature without breaking users code.

### CODE REVIEW

**Comment by MrPointer** [comment]
Whoa, that's a lot of changes! First of all, thank you so much for all this contribution!
However, we've created the [CONTRIBUTION.md](https://github.com/arduino-cmake/arduino-cmake/blob/release/2.0.0/CONTRIBUTING.md) for a reason, and if I'm not mistaken, you've suggested this in the first place.
It states that any feature will be implemented in a separate branch and then merged to the mainline development stream, not interfering with the current upcoming release, if there's one at all. 
You contributed so much code and introduced so many changes that I can't even review them in a single **Pull-Request**. Don't get me wrong, this is great! But I think it all should be separated to multiple features (thus branches and PRs), and merged to the `develop` branch instead, set for our next release.

I will review all your contribution once it's done. Yet again - Thank you.

**Review by MrPointer — CHANGES_REQUESTED** [review]
Whoa, that's a lot of changes! First of all, thank you so much for all this contribution!
However, we've created the [CONTRIBUTION.md](https://github.com/arduino-cmake/arduino-cmake/blob/release/2.0.0/CONTRIBUTING.md) for a reason, and if I'm not mistaken, you've suggested this in the first place.
It states that any feature will be implemented in a separate branch and then merged to the mainline development stream, not interfering with the current upcoming release, if there's one at all. 
You contributed so much code and introduced so many changes that I can't even review them in a single **Pull-Request**. Don't get me wrong, this is great! But I think it all should be separated to multiple features (thus branches and PRs), and merged to the `develop` branch instead, set for our next release.

I will review all your contribution once it's done. Yet again - Thank you.

**Comment by fraillt** [comment]
Sorry for inconvenience, and I apologize for being careless, but i'm not sure I completely understand what should I do next :) (i'm really bad at managing stuff, fortunately better at coding :) ) 

As I understand when *release/x.x.0* branch is active, any further development for this release is stopped (except bugfixes).

What should I do with this PR, it contains feature additions, bugfixes and code refactoring all in one...

Looking at these changes from user perspective only last commit is a feature, because it introduced new functionality for a user. 
All other changes probably could be viewed as a bugfix/enchancement. e.g: not being able to build for leonardo board sounds like a bug from user perspective, and these changes mostly addresses issues related to usb boards.

@MrPointer what do you suggest me to do in this situation, to make it convenient for all of us ? :)

Is it okay to if I remove [last commit](https://github.com/arduino-cmake/arduino-cmake/pull/29/commits/f24872ce15dabeafbafe91661716788fdeb2e00d) from this PR and make new PR request to develop branch?

P.S. I'll try be more careful in the future.

**Comment by MrPointer** [comment]
@fraillt Yes, you understand correctly - Once a `release` branch is active, any bug fixes are committed straight to the branch, while **features** are generally delayed for the next release.
I'd say that usually a **release** is not being marked as active until all developed features are finished and merged to the `development` line. However, currently we're in a bit of a rush to make a release since there's too much that has been changed from the [1st release](https://github.com/arduino-cmake/arduino-cmake/releases/tag/1.0.0). 
So in my opinion, all further development should be *frozen* until the next release, And by *frozen* I mean it shouldn't be merged to the active `release` branch, but to `develop` instead. The **release** then doesn't have to be delayed much - It can be published even a week after the latest release has been out. 

As for the PRs you should make:
IMO, you should create a separate branch for:
* USB support, including:
    * C++ 11 standard definition
    * Refactoring of `BoardFlags`
    * Overriding USB properties
* Library-related bug fixes
* ASM support

Only **Library-related bug fixes** and **ASM support** should make it to the upcoming release, while USB support should be marked for the next one. I make this decision since not so many people depend on the USB feature for this project to function properly, thus is can be delayed a bit, especially since it introduces changes to the public API. I hope that we agree on this :)

**Comment by fraillt** [comment]
Created two PR for ASM and bugfixes.

**Pull request closed without merging**
