### PR TITLE
Adding additional quotes removed. 

### PR DESCRIPTION
**Pull request by noseglasses**
The quotes where introduced as an intermediate fix. It turned out that this type of quoting is better added to Arduino's boards.txt or platforms.txt.

### CODE REVIEW

**Review by MrPointer — COMMENTED** [review]
Could it somehow affect others depending on it? Maybe I misunderstood you, but from your writing I get the impression that you've manually edited `boards.txt` and `programmer.txt` files for this to work.

**Comment by noseglasses** [comment]
No, it's the other way round. I initially introduced the quotes as a workaround in a previous PR. It now turned out that it is more correct to add the quotes to the broken *.txt files and remove the auto-quoting. Else, we would run a risk to have redundant quotes under certain circumstances.

**Comment by MrPointer** [comment]
@noseglasses How did these files got "broken" in the first place?

**Comment by noseglasses** [comment]
There is a `boards.txt` that contains the following line.

```
model01.build.extra_flags={build.usb_flags} -DKALEIDOSCOPE_HARDWARE_H="Kaleidoscope-Hardware-Model01.h"
```
The problem here is that the double quotes around `Kaleidoscope-Hardware-Model01.h` disappear when used with arduino-cmake and persist when used with arduino-builder. 

The following line from one of the C++ source files explains why those double quotes are required.
```cpp
#include KALEIDOSCOPE_HARDWARE_H
```

Fixing the respective `boards.txt` as
```
model01.build.extra_flags={build.usb_flags} '-DKALEIDOSCOPE_HARDWARE_H="Kaleidoscope-Hardware-Model01.h"'
```
by adding additional single quotes resolves the issue.

In my opinion modifying `boards.txt` here is more correct than adding quotes from inside of cmake-arduino. Unfortunately I am lacking time to dive deeper into the issue to find out why it works with one build system but not the other.

**Comment by MrPointer** [comment]
@noseglasses Thanks for the thorough explanation, really helpful 😃 

Well the problem is, as you've said, you can't assure it will work as expected on all build systems and platforms, which makes it very unstable.
The purpose of this library (And every library I guess) is to create a stable code line, and such assumptions really help drive it away from that goal.
My point is that we can't just accept a solution like this, temporary as it'll be, since it may completely break others' builds, leading to a *void state* where there is no compromise solution. 
Could you maybe keep this change only in your fork? I know it's not the most intuitive solution, but until we find an alternative, I think this is the best we can do.

**Comment by noseglasses** [comment]
> My point is that we can't just accept a solution like this, temporary as it'll be, since it may completely break others' builds, leading to a void state where there is no compromise solution.

The thing is, you already accepted the temporary fix [here](https://github.com/arduino-cmake/arduino-cmake/commit/42a3667542dd6ac5a9142f89d2ca28913d80e0f6). This PR intents to revert it.

The reason why the project I am working on does build with arduino-builder but not with arduino-cmake is that the former probably uses some sort of system command to run the compiler. This avoids using a shell that would otherwise remove double quotes. Arduino-cmake on the other hand generates a compiler command for the build step. This command appears to be executed in a way that the double quotes get removed. Not sure what happens under the hood. 

Another option how to deal with the quoting problem in arduino-cmake would be to identify all those variables read from `boards.txt` (and possibly other spec files) that actually represent command line arguments of any type (or sequences of those), then tokenize those variables (they might consist of multiple cmd. arg specifications), then quote the tokens and finally concatenate them. This would be the most clear solution. But we would have to be carefully not to add redundant quotes. That's pretty complex and I am not sure if it is what we want.

**Review by MrPointer — APPROVED** [review]
@noseglasses  I know that those quotes existed, just had to be sure that we don't make a mistake removing them.
Thanks again for your contribution!

**Pull request merged**
